### PR TITLE
Fedora migrate

### PR DESCRIPTION
**Pull request by straleyb**
Adds rake task for migrating fedora3 server to a fedora4 server

### CODE REVIEW

**Comment by terrellt** [comment]
Needs rebased. I'm not sure what to do here - do we just merge this and deal with actually running it later?

**Comment by straleyb** [comment]
I'd say merging it and then running it later would be the best here. Having everything set up so the migration can happen early sounds good. Actually doing the migration seems like a discussion that will be had.

**Comment by jechols** [comment]
The test commit and something else are missing post-rebase.  If @terrellt still has those commits, we need to get them back in.  If not... we need to recreate them.

**Comment by straleyb** [comment]
@jechols Well I didn't even notice. Its ok though. I understand what I was doing wrong in my tests now, so I'll rewrite them on my end, and then @terrellt Could even review them too.

**Comment by jechols** [comment]
Okay so now those commits are back but it says it can't merge again.

**Comment by terrellt** [comment]
Yeah, @straleyb wanted me to force push it.

**Pull request merged**
