### PR TITLE
Revert to active_fedora-noid 0.3.0

### PR DESCRIPTION
**Pull request by jechols**
Pins us to 0.3.0

### CODE REVIEW

**Comment by terrellt** [comment]
CI's displeased.

**Comment by jechols** [comment]
@terrellt Yeah, I'm dumb.  A lot of stuff was added to AF::Noid 1.0 which we use for better bucketing of assets :)  I'm hoping the new NOID 0.7.2 fixes everything, but I have to actually remove all our weird AF::Noid code first.

**Comment by jechols** [comment]
"A lot of stuff" == treeifier, it turns out

**Comment by jechols** [comment]
Okay, *now* we're ready I think

**Pull request merged**
