### PR TITLE
fixes #118 add font

### LINKED ISSUE #118: Add "Gudea, Helvetica, Verdana, sans-serif" font stack across the site.

### PR DESCRIPTION
**Pull request by mccallum**
adds font-stack through Bootstrap (including going out to Google for Gudea font)

fixes #118

### CODE REVIEW

**Comment by terrellt** [comment]
@mccallum Is this layout file taken from OD1?

**Comment by mccallum** [comment]
Yes. Should I take all that out?

**Comment by terrellt** [comment]
@mccallum I think so. It contains some stuff for sets that aren't really true anymore - like splitting on ":". Plus, were we moving from bootstrap classes to SASS mixins?

**Comment by mccallum** [comment]
Yes to SASS mixins route. I'll clean it up.

**Pull request merged**
